config/routes.rb
Rails.application.routes.draw do
  resources :sliders

  get 'home/index'

  devise_for :users
  get 'welcome/index'
   get '/about-us'=> 'welcome#about'

 

  resources :contacts,only: [:new,:create]
  resources :carriers,only: [:new,:create]
  resources :portfolios
   resources :sliders

 root 'welcome#index'

end

app/models/carrier.rb
class Carrier < ActiveRecord::Base
	mount_uploader :resume, ResumeUploader
		mount_uploader :photo, PhotoUploader
	validates :first_name, :last_name, :city, :country, :email_address, :resume,:photo, presence:true
	validates :phone_number, numericality: true,
                    length: { is: 10 }

end

app/models/contact.rb
class Contact < ActiveRecord::Base

	validates :name, :address, :email, :comments, presence:true	 
end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
  belongs_to :user
  mount_uploader :image, ImageUploader
  validates :name, :description, presence:true
end

app/models/slider.rb
class Slider < ActiveRecord::Base
  belongs_to :user
  mount_uploader :images, ImagesUploader
  validates :name, :description, :slide, presence:true
   
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable, :timeoutable
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  protected
  def after_sign_in_path_for(resource)
    home_index_path
  end
  def after_sign_out_path_for(resource)
    new_user_session_path
  end

end

app/controllers/carriers_controller.rb
class CarriersController < ApplicationController
	def new
		 @carrier =Carrier.new
	end
	
	def create
    	@carrier = Carrier.new(carrier_params)

    	respond_to do |format|
      		if @carrier.save
      			  CarrierMailer.carrier_email(@carrier).deliver
         
         
        		format.html { redirect_to new_carrier_path, notice: 'resume was successfully uploaded.' }
        		format.json { render :show, status: :created, location: @carrier }
      		else
        		format.html { render :new }
        		format.json { render json: @carrier.errors, status: :unprocessable_entity }
      		end
    	end
  	end
  
end
private
    def carrier_params
      params.require(:carrier).permit(:first_name, :last_name, :city, :country, :email_address, :phone_number, :resume, :photo)
  
	end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController
    protected
     def after_confirmation_path_for(resource_name, resource)
      if signed_in?(resource_name)
        home_index_path
      else
        new_session_path(resource_name)
      end
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def index
	end
	def new
	
	 @contact =Contact.new
  end
  def show
    
  end

  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
         ContactMailer.contact_email(@contact).deliver
         
        format.html { redirect_to new_contact_path, notice: 'contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end
  
end
private
    def contact_params
      params.require(:contact).permit(:name, :email,:address, :comments)
  
	end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only: [:show, :edit, :update, :destroy]

  # GET /portfolios
  # GET /portfolios.json
  def index
    @portfolios = Portfolio.all
  end

  # GET /portfolios/1
  # GET /portfolios/1.json
  def show
  	@portfolio = Portfolio.find(params[:id])
  end

  # GET /portfolios/new
  def new
    @portfolio = Portfolio.new
  end

  # GET /portfolios/1/edit
  def edit
  end

  # POST /portfolios
  # POST /portfolios.json
  def create
    @portfolio = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio.save
        format.html { redirect_to @portfolio, notice: 'Portfolio was successfully created.' }
        format.json { render :show, status: :created, location: @portfolio }
      else
        format.html { render :new }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /portfolios/1
  # PATCH/PUT /portfolios/1.json
  def update
    respond_to do |format|
      if @portfolio.update(portfolio_params)
        format.html { redirect_to @portfolio, notice: 'Portfolio was successfully updated.' }
        format.json { render :show, status: :ok, location: @portfolio }
      else
        format.html { render :edit }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portfolios/1
  # DELETE /portfolios/1.json
  def destroy
    @portfolio.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Portfolio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_portfolio
      @portfolio = Portfolio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def portfolio_params
      params.require(:portfolio).permit(:name, :description, :image, :user_id)
    end
end

app/controllers/sliders_controller.rb
class SlidersController < ApplicationController
  before_action :set_slider, only: [:show, :edit, :update, :destroy]

  # GET /sliders
  # GET /sliders.json
  def index
    @sliders = Slider.all
  end

  # GET /sliders/1
  # GET /sliders/1.json
  def show
  end

  # GET /sliders/new
  def new
    @slider = Slider.new
  end

  # GET /sliders/1/edit
  def edit
  end

  # POST /sliders
  # POST /sliders.json
  def create
    @slider = Slider.new(slider_params)

    respond_to do |format|
      if @slider.save
        format.html { redirect_to @slider, notice: 'Slider was successfully created.' }
        format.json { render :show, status: :created, location: @slider }
      else
        format.html { render :new }
        format.json { render json: @slider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sliders/1
  # PATCH/PUT /sliders/1.json
  def update
    respond_to do |format|
      if @slider.update(slider_params)
        format.html { redirect_to @slider, notice: 'Slider was successfully updated.' }
        format.json { render :show, status: :ok, location: @slider }
      else
        format.html { render :edit }
        format.json { render json: @slider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sliders/1
  # DELETE /sliders/1.json
  def destroy
    @slider.destroy
    respond_to do |format|
      format.html { redirect_to sliders_url, notice: 'Slider was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slider
      @slider = Slider.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def slider_params
      params.require(:slider).permit(:name, :description, :slide, :images, :user_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carriers_helper.rb
module CarriersHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/sliders_helper.rb
module SlidersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/carriers/new.html.erb
<div class="row-fluid">
  <div class="span4 well">
 
      <h1>Description</h1>
      <p>
        Google is an American multinational corporation specializing in Internet-related services and products. These include online advertising technologies, search, cloud computing, and software. Most of its profits are derived from AdWords.Google was founded by Larry Page and Sergey Brin while they were Ph.D. students at Stanford University. Together they own about 14 percent of its shares but control 56 of the stockholder voting power through supervoting stock. They incorporated Google as a privately held company on September 4, 1998. 

        </p>

        <p>

       <b> Your profile details as seen by recruiters</b>
        Email :
        Mobile No. :
        Current Location :
        Total Experience :

       </p>
 

     
      
  </div>


  
  <div class="span4 well ">
    <h1>Resume</h1>
      <%= simple_form_for(@carrier) do |f| %>
        <div class="form-inputs">
          <%= f.input :first_name %>
          <%= f.input :last_name %>
          <%= f.input :city %>
          <%= f.input :country %>
          <%= f.input :email_address %>
          <%= f.input :phone_number %>
          <%= f.input :resume %>
          <%= f.input :photo %> 
    
        </div>

        <div class="form-actions">
          <%= f.button :submit %>

        </div>
      <% end %>
  </div>

</div>

app/views/carriers/new.html.haml
.row-fluid
  .span6.well
    %h1 Description
    %p
      Google is an American multinational corporation specializing in Internet-related services and products. These include online advertising technologies, search, cloud computing, and software. Most of its profits are derived from AdWords.Google was founded by Larry Page and Sergey Brin while they were Ph.D. students at Stanford University. Together they own about 14 percent of its shares but control 56 of the stockholder voting power through supervoting stock. They incorporated Google as a privately held company on September 4, 1998.
    %p
      %b Your profile details as seen by recruiters
      %br
      %br Email :
      %br Mobile No. :
      %br Current Location :
      %br Total Experience :
  .span6.well
    %h1 Resume
    = simple_form_for(@carrier) do |f|
      .form-inputs
        = f.input :first_name
        = f.input :last_name
        = f.input :city
        = f.input :country
        = f.input :email_address
        = f.input :phone_number
        = f.input :resume
        = f.input :photo
        = f.submit:"Upload Resume",class:"btn btn-success"
      

app/views/contacts/new.html.erb
<h1>Contact Us</h1>
<%= simple_form_for(@contact) do |f| %>
  
  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :email %>
  
    <%= f.input :address %>
    <%= f.input :comments %>
  
    
    
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/contacts/new.html.haml
.row-fluid
  .span5.well
    %h1 Contact Us
    = simple_form_for(@contact) do |f|
      .form-inputs
        = f.input :name
        = f.input :email
        = f.input :address
        = f.input :comments
        = f.submit:"Create Contact",class:"btn btn-success"
  .span7.well
    %h1 Address
    %b United States
    %br 
    268 Bennett Avenue,
    Staten Island,
    NewYork, United States
    Phone:+19298884134
    %br
    %b India 
    %br
    Drishya building, KINFRA Filim & Video Park,
    Special Economic Zone, Sainik School P.O,
    Kazakuttam, Trivandrum-695585
    email:info@ideologysoft.com
    Phone: 0471 2167522 / 0471 2415022 

app/views/contacts/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @contact.address %>
</p>
<p>
  <strong>Comments:</strong>
  <%= @contact.comments %>
</p>

app/views/contacts/show.html.haml
%p
  %strong Name:
  = @contact.name
%p
  %strong Email:
  = @contact.email
%p
  %strong Address:
  = @contact.address
%p
  %strong Comments:
  = @contact.comments

app/views/home/index.html.haml
%h1 Home#index
%p Find me in app/views/home/index.html.haml

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Google" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>

          <%= link_to "Google",root_path,:class=>"brand" %>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Contact us", new_contact_path   %></li>
               <li><%= link_to "Carrier", new_carrier_path %></li>
              <li><%= link_to "About us", welcome_about_path %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">         
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=Edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Google"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    = stylesheet_link_tag "application", :media => "all"
    / For third-generation iPad with high-resolution Retina display:
    / Size should be 144 x 144 pixels
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    / For iPhone with high-resolution Retina display:
    / Size should be 114 x 114 pixels
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    / For first- and second-generation iPad:
    / Size should be 72 x 72 pixels
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    / For non-Retina iPhone, iPod Touch, and Android 2.1+ devices:
    / Size should be 57 x 57 pixels
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    / For all other devices
    / Size should be 32 x 32 pixels
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
  %body
    .navbar.navbar-fluid-top.navbar-inverse
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "Google",root_path,:class=>"brand"
            
          .container-fluid.nav-collapse
            %ul.nav
              - if user_signed_in?
                
                

                .dropdown
                  %button#dropdownMenu1.btn.btn-default.dropdown-toggle{"data-toggle" => "dropdown", :type => "button"}

                    Settings
                    %span.caret
                  %ul.dropdown-menu{"aria-labelledby" => "dropdownMenu1", :role => "menu"}
                    %li{:role => "presentation"}

                      =link_to "Edit User", edit_user_registration_path
                      =link_to "Sign out", destroy_user_session_path
                    
                    %li.divider{:role => "presentation"}
               
              - else
                %li= link_to "About us", about_us_path
                %li= link_to "Career", new_carrier_path
                %li= link_to "Contact us", new_contact_path
                
                %li= link_to "Portfolio" , portfolios_path
                %li= link_to "Sign in" , new_user_session_path
                
    .container-fluid
      .row-fluid
       

      
        .span9
          = bootstrap_flash
          = yield
      / /row
      %footer
        %center
          %p google.2014
    / /container

app/views/portfolios/_form.html.haml
= form_for @portfolio do |f|
  - if @portfolio.errors.any?
    #error_explanation
      %h2= "#{pluralize(@portfolio.errors.count, "error")} prohibited this portfolio from being saved:"
      %ul
        - @portfolio.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :image
    
   

app/views/portfolios/edit.html.haml
%h1 Editing portfolio

= render 'form'

= link_to 'Show', @portfolio

= link_to 'Back', portfolios_path

app/views/portfolios/index.html.haml
%h1 Listing Portpolios
%table
  %tr
    %th Name
    %th Description
    %th Image

    %th{:colspan => "3"}
  - @portfolios.each do |portfolio|
    %tr
      %td= portfolio.name
      %td= portfolio.description
      %td= image_tag portfolio.image
      %td= link_to 'Show', portfolio_path(portfolio)
      %td= link_to 'Edit', edit_portfolio_path(portfolio)
      %td= link_to 'Destroy', portfolio_path(portfolio),         |
          method: :delete, data: { confirm: 'Are you sure?' } |
= link_to 'New Portfolio', new_portfolio_path
%br
%br
.row-fluid
  .span3
    

app/views/portfolios/new.html.haml
%h1 New Portfolio
= simple_form_for(@portfolio) do |f|
  .form-inputs
    = f.input :name
    = f.input :description
    = f.hidden_field :user,value: current_user
    = f.input :image 

    = f.submit:"Upload Image",class:"btn btn-success"
      

app/views/portfolios/show.html.haml
%h1 Showing Portfolio
%p
  Name:
  
  = @portfolio.name
%p
  Description:
  
  = @portfolio.description
%p
  Image:
  
  = @portfolio.image
  %br
  = link_to "Back",portfolios_path |
  = link_to 'Destroy', @portfolio, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/sliders/_form.html.haml
= form_for @slider do |f|
  - if @slider.errors.any?
    #error_explanation
      %h2= "#{pluralize(@slider.errors.count, "error")} prohibited this slider from being saved:"
      %ul
        - @slider.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :slide
    = f.text_field :slide
  .field
    = f.label :images
    = f.file_field :images
    = f.hidden_field :user,value: current_user
    %br
    = f.submit:"Upload Image",class:"btn btn-success"
      

app/views/sliders/edit.html.haml
%h1 Editing slider

= render 'form'

= link_to 'Show', @slider

app/views/sliders/index.html.haml
%h1 Listing sliders

%table
  %tr
    
    %th Images
    
    %th
    %th
    %th

 
    
      
      
      
      #carousel-example-generic.carousel.slide{"data-ride" => "carousel"}
        / Indicators
        %ol.carousel-indicators
          %li.active{"data-slide-to" => "0", "data-target" => "#carousel-example-generic"}
          %li{"data-slide-to" => "1", "data-target" => "#carousel-example-generic"}   
     
        / Wrapper for slides
      
        - @sliders.each do |slider|
         
      
          = image_tag slider.images
    
           
      / Controls
      %a.left.carousel-control{"data-slide" => "prev", :href => "#carousel-example-generic", :role => "button"}
      %span.glyphicon.glyphicon-chevron-left
      %a.right.carousel-control{"data-slide" => "next", :href => "#carousel-example-generic", :role => "button"}
      %span.glyphicon.glyphicon-chevron-right


%br

= link_to 'New Slider', new_slider_path

app/views/sliders/new.html.haml
%h1 New slider

= render 'form'

app/views/sliders/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @slider.name
%p
  %b Description:
  = @slider.description
%p
  %b Slide:
  = @slider.slide
%p
  %b Images:
  = @slider.images

= link_to 'Edit', edit_slider_path(@slider)
\|
= link_to 'Back', sliders_path

app/views/welcome/about.html.erb
<h1>About Us</h1>
 <div class="well">
	Google is an American multinational corporation specializing in Internet-related services and products. These include online advertising technologies, search, cloud computing, and software. Most of its profits are derived from AdWords.

Google was founded by Larry Page and Sergey Brin while they were Ph.D. students at Stanford University. Together they own about 14 percent of its shares but control 56 of the stockholder voting power through supervoting stock. They incorporated Google as a privately held company on September 4, 1998. An initial public offering followed on August 19, 2004. Its mission statement from the outset was "to organize the world's information and make it universally accessible and useful, and its unofficial slogan was "Don't be evil.In 2006 Google moved to headquarters in Mountain View, California, nicknamed the Googleplex.

Rapid growth since incorporation has triggered a chain of products, acquisitions and partnerships beyond Google's core search engine. It offers online productivity software including email (Gmail), a cloud storage service (Google Drive), an office suite (Google Docs) and a social networking service (Google+). Desktop products include applications for web browsing, organizing and editing photos, and instant messaging. The company leads the development of the Android mobile operating system and the browser-only Chrome OS for a netbook known as a Chromebook. Google has moved increasingly into communications hardware: it partners with major electronics manufacturers in production of its high-end Nexus devices and acquired Motorola Mobility in May 2012. In 2012, a fiber-optic infrastructure was installed in Kansas City to facilitate a Google Fiber broadband service.

</div>

app/views/welcome/about.html.haml
.row-fluid
  
  .span12.well
    %h1 About Us

    =image_tag("about.jpeg") 
    %br
    %br

    Google is an American multinational corporation specializing in Internet-related services and products. These include online advertising technologies, search, cloud computing, and software. Most of its profits are derived from AdWords.
  
    Google was founded by Larry Page and Sergey Brin while they were Ph.D. students at Stanford University. Together they own about 14 percent of its shares but control 56 of the stockholder voting power through supervoting stock. They incorporated Google as a privately held company on September 4, 1998. An initial public offering followed on August 19, 2004. Its mission statement from the outset was "to organize the world's information and make it universally accessible and useful, and its unofficial slogan was "Don't be evil.In 2006 Google moved to headquarters in Mountain View, California, nicknamed the Googleplex.
 
  
    

app/views/welcome/index.html.erb
  <p>Google</p>
  

app/views/welcome/index.html.haml
.row-fluid
  .span12.well
    %h1 Welcome To Google